import {Container} from "inversify";
import "reflect-metadata";
import {WebSocketRouter} from "./routes/WebSocketRouter";
import {BattleMoveRoute} from "./routes/BattleMoveRoute";
import {UserService} from "./users/UserService";
import {SessionService} from "./users/SessionService";
import {PokemonLookup} from "./pokemon/PokemonLookup";
import {BattleService} from "./battles/BattleService";
import {PokemonSpawner} from "./pokemon/PokemonSpawner";
import {PokemonService} from "./pokemon/PokemonService";
import {WildEncounterService} from "./encounters/WildEncounterService";
import {WildEncounterGenerator} from "./encounters/WildEncounterGenerator";
import {WildEncounterRoute} from "./routes/WildEncounterRoute";
import {OwnedPokemonService} from "./pokemon/OwnedPokemonService";
import {TrainerService} from "./battles/TrainerService";
import {BattleTurnProcessor} from "./battles/BattleTurnProcessor";
import {MoveLookup} from "./moves/MoveLookup";
import {ActionPrioritiser} from "./battles/ActionPrioritiser";
import {BattleMoveActionProcessor} from "./battles/BattleMoveActionProcessor";
import {IBattleTurnProcessor} from "./battles/IBattleTurnProcessor";
import {DamageCalculator} from "./battles/DamageCalculator";
import {IPokemonService} from "./pokemon/IPokemonService";
import {BattleFaintProcessor} from "./battles/BattleFaintProcessor";

const container = new Container();

container.bind<ActionPrioritiser>(ActionPrioritiser).toSelf().inSingletonScope();
container.bind<BattleFaintProcessor>(BattleFaintProcessor).toSelf().inSingletonScope();
container.bind<BattleMoveActionProcessor>(BattleMoveActionProcessor).toSelf().inSingletonScope();
container.bind<BattleMoveRoute>(BattleMoveRoute).toSelf().inSingletonScope();
container.bind<BattleService>(BattleService).toSelf().inSingletonScope();
container.bind<DamageCalculator>(DamageCalculator).toSelf().inSingletonScope();
container.bind<IBattleTurnProcessor>(BattleTurnProcessor).to(BattleTurnProcessor).inSingletonScope();
container.bind<MoveLookup>(MoveLookup).toSelf().inSingletonScope();
container.bind<OwnedPokemonService>(OwnedPokemonService).toSelf().inSingletonScope();
container.bind<PokemonLookup>(PokemonLookup).toSelf().inSingletonScope();
container.bind<IPokemonService>(PokemonService).to(PokemonService).inSingletonScope();
container.bind<PokemonSpawner>(PokemonSpawner).toSelf().inSingletonScope();
container.bind<SessionService>(SessionService).toSelf().inSingletonScope();
container.bind<TrainerService>(TrainerService).toSelf().inSingletonScope();
container.bind<UserService>(UserService).toSelf().inSingletonScope();
container.bind<WebSocketRouter>(WebSocketRouter).toSelf().inSingletonScope();
container.bind<WildEncounterGenerator>(WildEncounterGenerator).toSelf().inSingletonScope();
container.bind<WildEncounterRoute>(WildEncounterRoute).toSelf().inSingletonScope();
container.bind<WildEncounterService>(WildEncounterService).toSelf().inSingletonScope();

export default container;
